name: release

on:
  push:

  repository_dispatch:
    types: [ AirMCU ]

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: python main.py

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "package_air_index.json"
          tag: "Nightly"
          allowUpdates: true
          