name: ssh
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      env:
        OSS_CONFIG: ${{ secrets.OSS_CONFIG }}
        OSS_NAME: ${{ secrets.OSS_NAME }}
      uses: mxschmitt/action-tmate@v3
